### ISSUE TITLE
what static site generator did you use

### ISSUE THREAD

**Issue by dkebler** [onury/onury.github.io#1]
TaskTimer...great...came across it a stackoverflow post glad you stuck it in there.

I was wondering what static site generator and templates you are using to build this.  Looks attractive, nicely laid out.

Are you willing to post the actual build repo?  I would like to see/use some of what you have done, at least the templates and styles.    

I've been working on this project

 https://github.com/dkebler/4S/tree/working-020

which is a super generic static site generator environment where one can plug in any "pieces" (e.g. use all three styling preprocessors at once, change the site generator), reconfigure the repo directory layout easily, plus publish to anywhere.  It has a built in cli that make it easy for non-programmers, but libraries can that be extended/modified or used as an api for even something like an online static site editor and publisher.   

BTW If you wanted to keep it private I have a private git server you can push it too.

**Comment by onury** [comment]
Thanks. Your project looks promising.

I build the documentations with **Docma**. A utility I wrote for my libs. Made it open source.
[Docma Repo](https://github.com/onury/docma)
[Docma documentation](https://onury.github.io/docma)
Just give credit if you're willing to use.
Cheers.
